### ISSUE TITLE
unexpected handling of zero-mag in vegamag units

### ISSUE THREAD

**Issue by douglase** [spacetelescope/pysynphot#100]
When I create an ArraySpectrum with flux=0 with abmag or stmag units pysynphot returns a flux near zero and the expected photlam rate. When the units are changed to vegamag the returned flux value is transformed to 28.6 and the photlam rate is ~10^-10 smaller than the expected count rate (which does appear consistent with  V=28.6 mags).  My understanding from the documentation is that these magnitude systems were normalized to be equivalent in Johnson-V band so this behavior is unexpected. 

Why is pysynphot changing the input flux value? 

Example code:
```
import pysynphot as S
sp = S.ArraySpectrum(wave=np.array([5510]),flux=np.array([0]),
                     fluxunits='vegamag',)
print([sp.flux,sp.fluxunits.name])
sp.convert("photlam") 
print([sp.flux,sp.fluxunits.name])

sp = S.ArraySpectrum(wave=np.array([5510]),flux=np.array([0]),
                     fluxunits='stmag',)
print([sp.flux,sp.fluxunits.name])
sp.convert("photlam")
print([sp.flux,sp.fluxunits.name])

print(S.__version__)
```

This Returns:

> [array([28.60766589]), 'vegamag']
[array([3.5268446e-09]), 'photlam']
[array([-3.97923226e-06]), 'stmag']
[array([1007.08552952]), 'photlam']
0.9.12

**Comment by pllim** [comment]
Turns out, you found a bug in the underlying VEGAMAG to PHOTLAM conversion. It is caused by the assumption during unit conversion from VEGAMAG to PHOTLAM that Vega is sampled in PHOTLAM, but it is not. In fact, by default, the Vega spectrum is given in FLAM.

Wrong answer (the one you found but boiled down to the relevant portion):

```python
>>> import numpy as np
>>> import pysynphot as S
>>> wave = np.array([5510])
>>> v = S.units.VegaMag()
>>> v.ToPhotlam(wave, 0)
array([3.5268446e-09])
```

This is because of this code in the conversion method:

https://github.com/spacetelescope/pysynphot/blob/cc032cdb9e362950bc1f7abecdadbcf45e728fb8/pysynphot/units.py#L1930-L1931

You can work around the bug by forcing Vega to convert to PHOTLAM first:

```python
>>> S.Vega.convert('photlam')
>>> v.ToPhotlam(wave, 0)
array([978.25635951])
```

To illustrated the second result is correct, let's check if it roundtrips:

```python
>>> ph = S.units.Photlam()
>>> ph.ToVegaMag(wave, v.ToPhotlam(wave, 0))
>>> array([-0.])
```

This bug aside, it is generally not recommended to define a spectrum directly in any magnitude unit. This is because some of the operations you can perform on the spectrum do not make sense in magnitude space because of the unit's non-linearity. Instead, please define your spectrum in PHOTLAM or FLAM, and convert to VEGAMAG only as the last step.

On the other hand, if your goal is unit conversion and not spectral manipulation (given that you only provided 1-element arrays in your example), please use [synphot](https://synphot.readthedocs.io/en/latest/), which works natively with Astropy units. For example:

```python
>>> from astropy import units as u
>>> from synphot import SourceSpectrum
>>> from synphot import units  # If you do not like this, you can import it as something else
>>> wave = 5510 * u.AA
>>> vegaspec = SourceSpectrum.from_vega()
>>> val_photlam = units.convert_flux(wave, 0 * units.VEGAMAG, 'photlam', vegaspec=vegaspec)
>>> val_photlam 
<Quantity 978.27554647 PHOTLAM>
>>> units.convert_flux(wave, val_photlam.reshape((1, )), 'vegamag',
...                    vegaspec==vegaspec)  # reshape is a temporary workaround
<Quantity [-0.] VEGAMAG>
```

**Comment by douglase** [comment]
Thanks for the quick response and suggestions!

**Comment by maxwellmb** [comment]
I just ran into this same bug when trying to create a FlatSpectrum in 'vegamag' units and spent half the day trying to figure out what was going on. I appreciate that I can use the I see that the bug is marked as closed, but it still seems to be an issue...

I appreciate that I can use the above workaround for now, but I'd imagine that for the future it's worth fixing the bug. Would something as simple as **resampled.convert("photlam")** at line 1931 solve the issue without affecting anything else?

**Comment by pllim** [comment]
@maxwellmb , you are welcome to open a PR but this package is not actively developed anymore.
